rails/config/routes.rb
Wasabi::Application.routes.draw do

  root 'feeds#index'

  resources :users do
    collection do
      get 'most_licked'
      get 'lick_the_most'
    end
  end

  resources :feeds
  get 'login' => 'login#index'
  post 'login' => 'login#auth'
  get 'logout' => 'logout#log_out'

  resources :licks, :only => :create
  resources :lick_licks, :only => :create
  resources :notifications, :only => :index
  resources :preferences, :only => :index

end

rails/app/models/achievement.rb
class Achievement < ActiveRecord::Base
	belongs_to :user

	validates_uniqueness_of :user, :scope => :type
	validates :user, presence: true

	# To be implemented by each subclass achievement.
	def self.check
		false
	end
end

rails/app/models/lick.rb
class Lick < ActiveRecord::Base
	belongs_to :sender, :class_name=>"User"
	belongs_to :receiver, :class_name=>"User"
	has_many :lick_licks
	after_commit :after_commit

	validates :sender, presence: true
	validates :receiver, presence: true

	def after_commit
		sender.update_lick_count
		receiver.update_lick_count
		check_achievements
	end

	def check_achievements
		puts 'chekcing achievmenets!'
		p Achievement.descendants

		achievements = []
		Achievement.descendants.each do |achievement|
			notice = achievement.check(self)
			if notice
				Notification.create(:text=>notice, :user=>sender)
			end
		end
		achievements
	end

	def create_notification
		Notification.create(:text=>"{sender.username} licked you!", :user=>receiver, :licker=>sender)
	end
	
	def get
		sender = self.sender
		receiver = self.receiver
		{
			:sender => {
				:id => sender.id,
				:username => sender.username
			},
			:receiver => {
				:id => receiver.id,
				:username => receiver.username
			},
			:created_at => self.created_at
		}
	end
end

rails/app/models/lick_back_achievement.rb
class LickBackAchivement < Achievement
	belongs_to :user
	
	def name
		'Lick Back'
	end

	def self.check(lick)
		puts self.class.name
		if Lick.where( {:sender => lick.receiver, :receiver => lick.sender } ).size()
			ach = LickBackAchivement.new
			ach.user = lick.sender
			ach.save
			name + ' Achievement earned!'
		end
	end
end

rails/app/models/lick_lick.rb
class LickLick < ActiveRecord::Base
	validates_uniqueness_of :licker, :scope => [:lick]
	validates :licker, presence: true
	validates :lick, presence: true

	after_save :update_lick_lick_count
	belongs_to :licker, :class_name => 'User'
	belongs_to :lick

	private

	def update_lick_lick_count
		self.lick.lick_lick_count += 1
		self.lick.save
	end
end

rails/app/models/notification.rb
class Notification < ActiveRecord::Base

	validates :user, presence: true

	belongs_to :user
	belongs_to :licker, :class_name=>'User'
end

rails/app/models/user.rb
class User < ActiveRecord::Base
	has_many :sent_licks, class_name: "Lick", foreign_key: "sender_id"
	has_many :received_licks, class_name: "Lick", foreign_key: "receiver_id"
	has_many :achievements
	has_secure_password

	def update_lick_count
		self.sent_licks_count = Lick.where(sender_id: id).count
		self.received_licks_count = Lick.where(receiver_id: id).count
		self.save!
	end
end

rails/app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
	respond_to :json

	def index
		@licks = Lick.all(:include => [:sender, :receiver, :lick_licks], :order => 'id DESC', :limit=>50 )
		#.to_json(:include => [{:sender => {:only=>'username'}}, {:receiver => {:only => 'username'}}], 
			#:only => [:created_at])
	end
end

rails/app/controllers/licks_controller.rb
class LicksController < ApplicationController
	def create
		@lick = Lick.new(licks_params)
		@lick.sender_id = session[:user_id]
		@lick.save

		ans = @lick.check_achievements
		if ans
			flash[:notice] = ans[0]
			p flash
		end

		render @lick
	end

	private
	def licks_params
		params.require(:lick).permit(:receiver_id)
	end
end

rails/app/controllers/login_controller.rb
class LoginController < ApplicationController
	def index
		@user = User.new
	end

	def auth
		user = User.find_by_username(login_params[:username]).try(:authenticate, login_params[:password])
		if user
			session[:user_id] = user.id
			redirect_to feeds_path
		else
			flash[:notice] = "Login failed."
			redirect_to login_path
		end
	end

	def log_out
		session[:user_id] = nil
	end

	private
	def login_params
		params.require(:user).permit(:username, :password)
	end
end

rails/app/controllers/logout_controller.rb
class LogoutController < ApplicationController
	def log_out
		session[:user_id] = nil
		redirect_to login_path
	end
end

rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
	respond_to :json

	def show
		@user = User.find(params[:id])
		@licks = Lick.where('sender_id = ? OR receiver_id = ?', params[:id], params[:id]).order(created_at: :desc).limit(100)

		@sent_count = @user.sent_licks_count
		@received_count = @user.received_licks_count
		@ratio = @received_count.fdiv(@sent_count)
		#@licks = @user.sent_licks + @user.received_licks

		#@licks = Lick.all(:include => [:sender, :receiver, :lick_licks], :order => 'created_at DESC' )

		# respond_with @user.get_profile
	end

	def new
		@user = User.new
	end

	def index
		@users = User.all
	end

	def create
		@user = User.create(user_params)
		if @user.save
			flash[:notice] = 'Account created!'
			session[:user_id] = @user.id
			redirect_to feeds_path
		else
			render 'new', :notice => 'Bad username/bassword!'
		end
	end

	def most_licked
		@users = User.all.order(received_licks_count: :desc)
	end

	def lick_the_most
		@users = User.all.order(sent_licks_count: :desc)
	end

	def user_params
		params.require(:user).permit(:username, :password, :password_confirmation)
	end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/app/helpers/feeds_helper.rb
module FeedsHelper
end

rails/app/helpers/lick_licks_helper.rb
module LickLicksHelper
end

rails/app/helpers/licks_helper.rb
module LicksHelper
end

rails/app/helpers/login_helper.rb
module LoginHelper
end

rails/app/helpers/logout_helper.rb
module LogoutHelper
end

rails/app/helpers/notifications_helper.rb
module NotificationsHelper
end

rails/app/helpers/preferences_helper.rb
module PreferencesHelper
end

rails/app/helpers/users_helper.rb
module UsersHelper
end

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Wasabi</title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/> <!--320-->
	</head>
	
	<body data-view="<%= params[:controller] %>#<%=params[:action]%>">

		<nav class="bar bar-tab">
			<%= link_to feeds_path, :class=>'tab-item', :id=>'feeds-tab' do %>
				<span class="icon icon-home"></span>
				<span class="tab-label">Home</span>
			<% end %>
			<% if session[:user_id] %>
				<%= link_to user_path(session[:user_id]), :class=>'tab-item', :id=>'profile-tab' do %>
					<span class="icon icon-person"></span>
					<span class="tab-label">Profile</span>
				<% end %>
			<% end %>

			<%= link_to notifications_path, :class=>'tab-item', :id=>'notifications-tab' do %>
				<span class="icon icon-star-filled"></span>
				<span class="tab-label">Notifications</span>
			<% end %>

			<%= link_to most_licked_users_path, :class=>'tab-item', :id=>'users-tab' do %>
				<span class="icon icon-search"></span>
				<span class="tab-label">Most Licked</span>
			<% end %>

			<%= link_to lick_the_most_users_path, :class=>'tab-item', :id=>'users-tab' do %>
				<span class="icon icon-search"></span>
				<span class="tab-label">Most Licker</span>
			<% end %>
			
			<%= link_to preferences_path, :class=>'tab-item', :id=>'preferences-tab' do %>
				<span class="icon icon-gear"></span>
				<span class="tab-label">Settings</span>
			<% end %>
			

		</nav>

		<header class="bar bar-nav">
			<% if session[:user_id] %>
				<button class="btn btn-link pull-left">
					<%= link_to User.find(session[:user_id]).username, user_path(session[:user_id]) %>
				</button>
			<% end %>
			<h1 class="title">wasabi</h1>
			<button class="btn btn-link pull-right">
				<% if session[:user_id] %>
					<%= link_to 'Log out', logout_path %>
				<% else %>
					<%= link_to 'Log in', login_path %>
				<% end %>
			</button>
		</header>
	
		<div class="content">
			<% if flash[:notice] %>
				<ul class="table-view">
					<% flash.each do |name, msg| %>
						<li class="table-view-cell"><%= msg %></li>
					<% end -%>
				</ul>
			<% end %>
			<%= yield %>
		</div>

	</body>
</html>